### ISSUE TITLE
Can't enchant (Incremental-RPG)

### ISSUE THREAD

**Issue by cahema** [TotomInc/totominc.github.io#33]
When i try to enchant my sword the button just do nothing.

**Comment by NewbiZ** [comment]
Same here.

I think the game is not finished. Reached level 60 yesterday, got all the stuff, and there isn't much to do.
- Quests are too hard (can't finish a level 30 quest without waiting for heal, even though I'm 60 full stuff)
- Not enough quests
- Not enough gear
- Cristals are useless? Got thousands of them but no idea how to spend it
- Amulets are missing

There's a lot of potentiel in this incremental game, please give it some love :)

**Comment by TotomInc** [comment]
Hey,

I can confirm, the game is not finished this is why enchantments doesn't work.

Actually, incremental rpg is not balanced, doesn't have have a lot of content and is maybe bugged at certain points.

Crystals are useless because I wanted to make an enchantment system which needs crystals.

I was looking for a new project in relation with incrementals games. I think I found what to do, a remake of incremental rpg but in HTML5 canvas, with pixels graphics. This will be the first time I use and learn about canvas, so don't expect something incredible! ;)

If you have any ideas (gameplay ideas for example) about the new project I want to make, feel free to let me know, on this issue if possible!

Thanks for playing incremental rpg!

**Comment by cahema** [comment]
Hi totominc.
I have to say i love the idea.
Im triying to learn some hhtp/css and javascript and do my own my game.
So i can help you when i finish learning to debug your games :D

**Comment by TotomInc** [comment]
No problem man, just take your time to learn enough!

Here is the repo of the new project : https://github.com/TotomInc/canvas-rpg
